config/routes.rb
Rails.application.routes.draw do
  class OnlyAjaxRequest
    def matches?(request)
      request.xhr?
    end
  end

  devise_for :users
  root 'home#index'
  
  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'

  resources :groups, only: [:create, :update, :destroy] do
    resources :categories, except: [:show, :new, :edit]
    get "categories/:id", to: "categories#get_category_ajax", constraint: OnlyAjaxRequest.new

    resources :products, except: [:show, :new, :edit]
    get "products/:id", to: "products#get_product_ajax", constraint: OnlyAjaxRequest.new
    post "products/post_product_by_category", to: "products#post_product_by_category_ajax", constraint: OnlyAjaxRequest.new

    resources :group_members, only: [:index, :create, :destroy], path: '/group-members'
    get "users/get_user", to: "users#get_user_ajax", constraint: OnlyAjaxRequest.new

    resources :transactions, except: [:new, :edit, :show]
    post "transactions/get_transaction", to: "transactions#get_transaction_ajax", constraint: OnlyAjaxRequest.new
    get "transactions/export", to: "transactions#export", as: :export_transactions
  end
  
  get "groups/:id", to: "groups#get_group_ajax", constraint: OnlyAjaxRequest.new
  post "groups/blocked/:id", to: "groups#post_group_blocked_ajax", constraint: OnlyAjaxRequest.new

  resources :users, except: [:create, :show]
  post "users/create", to: "users#create"
  get "users/ajaxValidateFieldUser", to: "users#ckeck_user_exists_ajax", constraint: OnlyAjaxRequest.new

  resources :data_files, only: [:index, :destroy], path: '/data-files' do
    get "download", on: :member
    delete "destroy_multi", on: :collection, constraint: OnlyAjaxRequest.new
  end

  resources :product_categories
end

app/models/data_file.rb
class DataFile < ApplicationRecord
  belongs_to :user
  belongs_to :group

  enum type_action_id: {
    Export: 1,
    Import: 2
  }

  scope :by_group, -> (group_id){group_id > 0 ? where(group_id: group_id) : all }
  scope :by_user, -> (user_id){ user_id > 0 ? where(user_id: user_id) : all }
  scope :by_type_action, ->(type_action_id){ type_action_id > 0 ? where(type_action_id: type_action_id) : all }
  scope :by_date, ->(from_date, to_date){ 
    from_date.blank? && to_date.blank? ? all : where(created_at: from_date..to_date + 1.day - 1.second)
  }
end

app/controllers/data_files_controller.rb
require 'json'

class DataFilesController < ApplicationController
  include CommonHelper

  load_and_authorize_resource
  before_action :find_data_file, only: [:destroy, :download]

  def index
    data_list
  end

  def destroy
    begin
      path_to_file = "#{Rails.root}#{@data_file.file_path}"
      File.delete(path_to_file) if File.exist?(path_to_file)
      @data_file.delete
      flash[:success] = t("model.data_file.message.deleted_success")

      redirect_to data_files_path
    rescue
    end
  end

  def download
    path_to_file = "#{Rails.root}#{@data_file.file_path}"
    exist_file = File.exist?(path_to_file)

    if exist_file
      send_file(
        path_to_file,
        filename: "#{@data_file.file_name}",
        type: "application/excel"
      )
    else
      respond_to do |format|
        flash[:danger] = t "model.data_file.message.path_not_found"
        format.html {redirect_to data_files_url}
      end
    end
  end

  def destroy_multi
    unless params[:data_file_ids].nil?
      data_file_ids = JSON.parse(params[:data_file_ids])
      # DataFile.where(:id => data_file_ids).destroy_all
      
      data_file_ids.each do |data_file_id|
        data_file = DataFile.find_by_id data_file_id
        path_to_file = "#{Rails.root}#{data_file.file_path}"
        File.delete(path_to_file) if File.exist?(path_to_file)
        data_file.delete
      end

      flash[:success] = t("model.data_file.message.deleted_success")

      respond_to do |format|
        format.json {render :json => {:status => "true"}}
      end
    end
  end

  private
  def find_data_file
    @data_file = DataFile.find_by_id params[:id]

    if @data_file.nil?
      flash[:danger] = t "model.data_file.message.not_found"

      redirect_to data_files_path
    end
  end

  def form_params
    types = {t("common.form.all_selection") => 0}
    @type_actions_search = types.merge!(DataFile.type_action_ids)

    @groups = get_select_groups true, true
    @users = get_select_users true, true
  end

  def search_params
    @group_id = params[:group_file_id].to_i
    @from_date = to_date(params[:from_date]) unless params[:from_date].nil?
    @to_date = to_date(params[:to_date]) unless params[:to_date].nil?
    @type_action_id = params[:type_action_id] ? params[:type_action_id].to_i : 0
    @user_id = params[:user_id] ? params[:user_id].to_i : 0
  end

  def data_list
    search_params
    @data_files = DataFile.includes(:user).includes(:group)
                                          .by_group(@group_id)
                                          .by_type_action(@type_action_id)
                                          .by_user(@user_id)
                                          .by_date(@from_date, @to_date)
                                          .order(created_at: :desc)
    form_params
  end
end

app/views/data_files/_list.html.erb
<div class="col-md-12 table-responsive" id="table_wapper">
  <div class="row">
    <table class="table table-striped table-bordered table-hover dataTable 
      no-footer display" id="table-data-file">
      <thead>
        <tr>
          <th width="7%" class="text-align-left"><input type="checkbox" id="check-title"></th>
          <th width="15%"><%= t("model.data_file.created_date") %></th>
          <th><%= t("model.data_file.type.file_name") %></th>
          <th><%= t("model.data_file.type.user_id") %></th>
          <th><%= t("model.data_file.type.group_id") %></th>
          <th width="10%"><%= t("model.transaction.type.type_action_id") %></th>
          <th width="8%"><%= t("common.form.action") %></th>
        </tr>
      </thead>

      <tbody id="data-file-body">
        <% if @data_files.any? %>
          <% created_date_array = [] %>

          <% @data_files.each do |data_file| %>
            <tr>
              <td><input type="checkbox" data-id="<%= data_file.id %>" class="row-check"></td>
              <td><%= data_file.created_at.strftime("%m/%d/%Y") %></td>
              <td><a href="<%= download_data_file_path(:id => data_file.id) %>">
                <%= data_file.file_name %></a></td>
              <td><%= data_file.user.full_name %></td>
              <td><%= data_file.group.name %></td>
              <td><%= data_file.type_action_id %></td>
              <td>
                <a href="<%= download_data_file_path(:id => data_file.id) %>">
                  <i class="glyphicon glyphicon-download-alt" data-toggle="tooltip" 
                    data-placement="top" title="<%= t("common.form.download") %>"></i>
                </a>

                <a href="#modal-deletion" class="data-file-delete" 
                  data-id="<%= data_file.id %>" data-toggle="modal">
                  <i class="glyphicon glyphicon-trash glyphicon" 
                    data-id="<%= data_file.id %>" data-toggle="tooltip" 
                    data-placement="top" title="<%= t("common.form.delete") %>"></i>
                </a>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="8" align="center"><%= t("common.table.empty") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="col-md-12 row">
  <a href="javascript:void(0)" class="btn custom-btn-green" id="delete-row-button"
    data-toggle="modal">
    <span data-toggle="tooltip" data-placement="right" title="<%= t("common.delete_selected") %>">
      <%= t("common.form.delete") %>
    </span>
  </a>
</div>

app/views/data_files/_script.html.erb
<% content_for :scripts do %>
  <script type="application/javascript">
    $(document).ready(function() {
      initChosen("group_id");
      initChosen("user_id");
      setParamsSearch();

      $("#frm-search-file").validationEngine({
        promptPosition: "inline",
        addSuccessCssClassToField: "no-error",
        addFailureCssClassToField: "has-error",
        validateNonVisibleFields: true,
        prettySelect : true,
        useSuffix: "_chosen"
      });

      $(document).on("click", ".glyphicon-trash.glyphicon", function () {
        var id = $(this).data('id');
        document.getElementById("btn-confirm-delete").href = "/data-files/" + id
      });

      $("#frm-search-file").on("click", ".reset", function() {
        resetSearch();
      });

      $("#frm-search-file").on("click", ".search", function() {
        $("#frm-search-file").submit();
      });

      $("#delete-row-button").on("click", function() {
        displayDialogDelete();
      });

      // set check all
      $("#check-title").on("click", function() {
        var isChecked = $(this).is(":checked");

        $("#data-file-body input:checkbox").each(function () {
          if(isChecked == true){
            $(this).prop('checked', true);
          }else{
            $(this).prop('checked', false);
          }
        });
      });

      $(".row-check").on("change", function() {
        var totalChecked = $("#data-file-body input:checkbox:checked").length;
        var totalCheckbox = $("#data-file-body input:checkbox").length;
        
        if (totalChecked == totalCheckbox) {
          $("#check-title").prop('checked', true);
        } else {
          $("#check-title").prop('checked', false);
        }
      });
    });

    function resetSearch() {
      $("#start_date").val("");
      $("#end_date").val("");
      $("#group_id").val(0);
      $("#group_id").trigger("chosen:updated");
      $("#user_id").val(0);
      $("#user_id").trigger("chosen:updated");
      $("#type_action_id").val(0);
    }

    function setParamsSearch() {
      <% unless params[:from_date].blank? %>
        var from_date = moment('<%= params[:from_date] %>').format('L');
      <% else %>
        var from_date = "";
      <% end %>

      <% unless params[:to_date].blank? %>
        var to_date = moment('<%= params[:to_date] %>').format('L');
      <% else %>
        var to_date = "";
      <% end %>

      <% unless params[:type_action_id].blank? %>
        var type_action_id = "<%= params[:type_action_id] %>";
      <% else %>
        var type_action_id = 0;
      <% end %>

      <% unless params[:group_file_id].blank? %>
        var group_id = "<%= params[:group_file_id] %>";
      <% else %>
        var group_id = 0;
      <% end %>

      <% unless params[:user_id].blank? %>
        var user_id = "<%= params[:user_id] %>";
      <% else %>
        var user_id = 0;
      <% end %>

      $("#group_id").val(group_id);
      $("#group_id").trigger("chosen:updated");
      $("#user_id").val(user_id);
      $("#user_id").trigger("chosen:updated");
      $("#type_action_id").val(type_action_id);
      $("#start_date").val(from_date);
      $("#end_date").val(to_date);
    }

    function displayDialogDelete() {
      $("#dialog-messages").dialog({
        closeOnEscape: false,
        open: function(event, ui) {
          $("#lblmessages").html("<%= t('common.form.delete_multi_msg') %>");
          $("#dialog-messages .alert").addClass("alert-warning");
          $(".ui-dialog-titlebar-close", ui.dialog | ui)
            .css("margin-top", "-10px")
            .css("margin-right", "4px")
            .css("color", "red");
        },
        width: 400,
        modal: true,
        buttons: [
          {
            id: "btnDelete",
            text: "<%= t('common.form.delete') %>",
            class: "btn btn-danger",
            click: function () {
              var data_file_ids = [];

              $("#data-file-body input[type=checkbox]").each(function() {
                if ($(this).is(":checked")) {
                  data_file_ids.push($(this).data("id"));
                }
              });

              url = "/data-files/destroy_multi?data_file_ids=[" + data_file_ids + "]";

              $.ajax({
                url: url,
                cache: false,
                type: "DELETE",
                success: function (data) {
                  if (data.status == "true") {
                    window.location.replace("<%= data_files_path %>");
                  }
                }
              });
              $(this).dialog('close');
            }
          },
          {
            id: "btnCancel",
            text: "<%= t('common.form.cancel') %>",
            class: "btn btn-default",
            click: function () {
              $(this).dialog('close');
            }
          }
        ]
      });
    }
  </script>
<% end %>

app/views/data_files/_script_datatable.html.erb
<% content_for :scripts do %>
  <script type="application/javascript">
    var responsiveHelper_dt_basic = undefined;
    var responsiveHelper_datatable_fixed_column = undefined;
    var responsiveHelper_datatable_col_reorder = undefined;
    var responsiveHelper_datatable_tabletools = undefined;
    var breakpointDefinition = {
      tablet : 1024,
      phone : 480
    };
    $('#table-data-file').dataTable({
      "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
      "t"+
      "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
      "autoWidth" : true,
      "oLanguage": {
        "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
      },
      "preDrawCallback" : function() {
        if (!responsiveHelper_dt_basic) {
          responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#table-data-file'), breakpointDefinition);
        }
      },
      "rowCallback" : function(nRow) {
        responsiveHelper_dt_basic.createExpandIcon(nRow);
      },
      "drawCallback" : function(oSettings) {
        responsiveHelper_dt_basic.respond();
      }
    });
  </script>
<% end %>

app/views/data_files/_search.html.erb
<%= form_for :data_file, :html=> {:id => "frm-search-file", :method => "GET", 
  :enforce_utf8 => false, :class => "form-horizontal"} do |f| %>
   <div class="col-md-6">
    <div class="form-group">
      <%= f.label :group_id, t("model.data.type.group_id"), class: "col-md-4 control-label" %>

      <div class="col-md-6 custom-chosen">
        <%= f.collection_select :groups, @groups, :id, :name.to_s,{prompt: false}, 
          {class: "chosen-select form-control", name: "group_file_id", id: "group_id"} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :user_id, t("model.data.type.user_id"), class: "col-md-4 control-label" %>

      <div class="col-md-6 custom-chosen">
        <%= f.collection_select :user_id, @users, :id, :full_name.to_s,{prompt: false},
          {class: "chosen-select form-control", name: "user_id", id: "user_id"} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :type_action_id, t("model.model.data_file.type.type_action_id"), 
        class: "col-md-4 control-label" %>

      <div class="col-md-6">
        <%= f.select :type_action_id, @type_actions_search, {}, 
          {class: "form-control", name: "type_action_id", id: "type_action_id"} %>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :from_date, t("model.transaction.label.from_date"), 
        class: "col-md-4 control-label" %>

      <div class="col-md-6">
        <label class="input"><i class="icon-append fa fa-calendar"></i>
          <%= f.text_field :from_date, {id: "start_date", name: "from_date",
            class: "datepicker form-control validate[funcCall[isDate], dateRange[version_date]]", 
            "data-dateformat" => "mm/dd/yy", placeholder: "MM/DD/YYYY", 
            onchange: "hidenErrorDateRange('start_date', 'end_date');"} %>
        </label>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :to_date, t("model.transaction.label.to_date"), 
        class: "col-md-4 control-label" %>

      <div class="col-md-6">
        <label class="input"><i class="icon-append fa fa-calendar"></i>
          <%= f.text_field :to_date, {name: "to_date", id: "end_date",
            class: "datepicker form-control validate[funcCall[isDate], dateRange[version_date]]",
            "data-dateformat" => "mm/dd/yy", placeholder: "MM/DD/YYYY", 
            onchange: "hidenErrorDateRange('start_date', 'end_date');"} %>
        </label>
      </div>
    </div>
  </div>

  <div class="col-sm-5 col-sm-offset-5">
    <button type="button" class="btn custom-btn-green search"><%= t("common.form.search") %></button>
    <button type="button" class="btn btn-default reset"><%= t("common.form.reset") %></button>
  </div>
<% end %>
<div class="clearfix"></div>

app/views/data_files/index.html.erb
<% content_for :ribbon do %>
  <div id="ribbon">
    <a href="/"><i class="fa fa-cogs fa-lg"></i></a>
    <ol class="breadcrumb">
      <li><a href="#"><%= t("common.form.administrator") %></a></li>
      <li>
        <a href="<%= data_files_path %>">
          <%= t("model.data_file.model_name") %>
        </a>
      </li>
      <li><%= t("common.form.list") %></li>
    </ol>
  </div>
<% end %>

<article class="col-sm-12 col-md-12 col-lg-12">
  <div class="custom-widget">
    <header role="heading">
      <div class="col-xs-8 title">
        <h5>
          <%= t("model.data_file.title.list") %>
        </h5>
      </div>
    </header>

    <div class="wg-content">
      <div class="row search-content" id="data-file-search">
        <%= render "search" %>
      </div>
      <div class="row listing-container" id="list-data-file">
        <%= render "list" %>
      </div>
    </div>
  </div>
</article>

<% if @data_files.any? %>
  <%= render "script_datatable" %>
<% end %>

<%= render "shared/deletion" %>
<%= render "shared/dialog"%>
<%= render "script" %>