config/routes.rb
Rails.application.routes.draw do
  class OnlyAjaxRequest
    def matches?(request)
      request.xhr?
    end
  end

  devise_for :users
  root 'home#index'
  
  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'

  resources :groups, only: [:create, :update, :destroy] do
    resources :categories, except: [:show, :new, :edit]
    get "categories/:id", to: "categories#get_category_ajax", constraint: OnlyAjaxRequest.new

    resources :products, except: [:show, :new, :edit]
    get "products/:id", to: "products#get_product_ajax", constraint: OnlyAjaxRequest.new
    post "products/post_product_by_category", to: "products#post_product_by_category_ajax", constraint: OnlyAjaxRequest.new

    resources :group_members, only: [:index, :create, :destroy], path: '/group-members'
    get "users/get_user", to: "users#get_user_ajax", constraint: OnlyAjaxRequest.new

    resources :transactions, except: [:new, :edit, :show]
    post "transactions/get_transaction", to: "transactions#get_transaction_ajax", constraint: OnlyAjaxRequest.new
    get "transactions/export", to: "transactions#export", as: :export_transactions
  end
  
  get "groups/:id", to: "groups#get_group_ajax", constraint: OnlyAjaxRequest.new
  post "groups/blocked/:id", to: "groups#post_group_blocked_ajax", constraint: OnlyAjaxRequest.new

  resources :users, except: [:create, :show]
  post "users/create", to: "users#create"
  get "users/ajaxValidateFieldUser", to: "users#ckeck_user_exists_ajax", constraint: OnlyAjaxRequest.new

  resources :data_files, only: [:index, :destroy], path: '/data-files' do
    get "download", on: :member
    delete "destroy_multi", on: :collection, constraint: OnlyAjaxRequest.new
  end

  resources :product_categories
end

app/controllers/transactions_controller.rb
require 'rubyXL'
require 'fileutils'

class TransactionsController < ApplicationController
  include CommonHelper, RubyXL

  load_and_authorize_resource
  before_action :find_transaction, only: [:update, :destroy, :get_transaction_ajax]

  def index
    get_list_data
  end

  def create
    @transaction = Transaction.new transaction_params
  
    if @transaction.save
      if @transaction.type_id == "Expense"
        group = Group.find_by_id @transaction.group_id
        group.saved_money = group.saved_money - @transaction.amount
        group.save!
      else
        group = Group.find_by_id @transaction.group_id
        group.saved_money = group.saved_money + @transaction.amount
        group.save!
      end

      # get_list_data      
      # render template: "transactions/_list", layout: false

      flash[:success] = t('model.transaction.message.add_success')
      msg = {:status => "true", :transaction => @transaction}

      respond_to do |format|
        format.json {render :json => msg}
      end     
    end
  end

  def update
    amount_old = @transaction.amount
    
    if @transaction.update transaction_params
      if @transaction.type_id == "Expense"
        group = Group.find_by_id @transaction.group_id
        group.saved_money = group.saved_money + amount_old - @transaction.amount
        group.save!
      else
        group = Group.find_by_id @transaction.group_id
        group.saved_money = group.saved_money - amount_old + @transaction.amount
        group.save!
      end

      # get_list_data
      # render template: "transactions/_list", layout: false

      flash[:success] = t('model.transaction.message.update_success')
      msg = {:status => "true", :transaction => @transaction}

      respond_to do |format|
        format.json {render :json => msg}
      end    
    end
  end

  def destroy
    if @transaction.delete
      if @transaction.type_id == "Expense"
        group = Group.find_by_id @transaction.group_id
        group.saved_money = group.saved_money + @transaction.amount
        group.save!
      else
        group = Group.find_by_id @transaction.group_id
        group.saved_money = group.saved_money - @transaction.amount
        group.save!
      end

      # get_list_data
      # render template: "transactions/_list", layout: false

      flash[:success] = t('model.transaction.message.deleted_success')
      msg = {:status => "true", :transaction => @transaction}

      respond_to do |format|
        format.json {render :json => msg}
      end        
    end
  end

  def get_transaction_ajax
    respond_to do |format|
      format.json {render :json => @transaction}
    end
  end

  def export
    list_transaction
    @master_types = Transaction.type_ids
    @group_members = GroupMember.includes(:group).includes(:user)
                                .where(group_id: params[:group_id])

    file_path_template = "#{Rails.root.to_s}/files/templates/transaction.xlsx"
    template = RubyXL::Parser.parse(file_path_template)

    #Parse file from template
    workbook = RubyXL::Parser.parse_buffer(template.stream.string)
    worksheet = workbook[0]
    worksheet_master = workbook[1]
    template.worksheets.delete(template[0])

    row_index = 4
    worksheet.data_validations = RubyXL::DataValidations.new
    formula_member = "=#{SHEET_MASTER_NAME}!$C$#{row_index + 1}:$C$#{row_index + @group_members.size}"
    formula_type = "=#{SHEET_MASTER_NAME}!$H$#{row_index + 1}:$H$#{row_index + @master_types.size}"
    worksheet.add_dropdown(4, 5, formula_member)
    worksheet.add_dropdown(4, 6, formula_type)

    fill_data_sheet_transaction worksheet
    fill_data_sheet_master worksheet_master

    export_file_name = "transaction_#{DateTime.now.strftime(FORMAT_DATE_FILE)}.xlsx"
    dir = "#{Rails.root.to_s}/tmp/files/export"
    FileUtils::mkdir_p(dir) unless Dir.exists?(dir) # check folder exists
    file_path_temp = "#{dir}/#{export_file_name}"

    workbook.write(file_path_temp)

    # create log file
    file_path_log = "/tmp/files/export/#{export_file_name}"
    create_data_file(export_file_name, file_path_log, current_user.id, 
      @group_id, DataFile.type_action_ids[:Export])

    send_file file_path_temp, :type => "application/excel", :x_sendfile => true
  end

  private
  def transaction_params
    if params[:transaction][:type_id].to_i == 2
      params[:transaction][:category_id] = 0
    end
    params[:transaction][:type_id] = params[:transaction][:type_id].to_i
    params[:transaction][:group_id] = params[:group_id].to_i
    params[:transaction][:user_id] = current_user.id

    params.require(:transaction).permit(:amount, :description, 
      :category_id, :group_id, :type_id, :user_id)
  end

  def find_transaction
    @transaction = Transaction.find_by_id params[:id].to_i

    if @transaction.nil?
      flash[:danger] = t "model.transaction.message.not_found"

      redirect_to group_transactions_url
    end
  end

  def get_list_data
    list_transaction
   
    @current_money = Group.find_by_id(@group_id).saved_money
    @categories = get_select_categories true, false
    
    types = {t("common.form.all_selection") => 0}
    @types_search = types.merge!(Transaction.type_ids)
    @categories_search = get_select_categories true, true
  end

  def list_transaction
    @group_id = params[:group_id].to_i
    @from_date = to_date(params[:from_date]) unless params[:from_date].nil?
    @to_date = to_date(params[:to_date]) unless params[:to_date].nil?
    @type_id = params[:type_id] ? params[:type_id].to_i : 0
    @category_id = params[:category_id] ? params[:category_id].to_i : 0

    @transactions = Transaction.includes(:user).by_group(@group_id)
                                              .by_category(@category_id)
                                              .by_type(@type_id)
                                              .by_date(@from_date, @to_date)
                                              .order("updated_at desc")

    @summary_income = 0
    @summary_expense = 0
  
    @transactions.each do |transaction|
      if transaction.type_id == "Expense"
        @summary_expense += transaction.amount
      else
        @summary_income += transaction.amount
      end
    end
    @summary_saved = @summary_income - @summary_expense
  end

  def fill_data_row worksheet, row_index, transaction, count
    worksheet.add_cell(row_index, 1, count)
    add_border_to_cell worksheet, row_index, 1

    worksheet.add_cell(row_index, 2, transaction.updated_at.strftime("%m/%d/%Y"))
    add_border_to_cell worksheet, row_index, 2

    worksheet.add_cell(row_index, 3, transaction.amount)
    add_border_to_cell worksheet, row_index, 3

    worksheet.add_cell(row_index, 4, transaction.description)
    add_border_to_cell worksheet, row_index, 4

    worksheet.add_cell(row_index, 5, transaction.user.full_name)
    add_border_to_cell worksheet, row_index, 5

    worksheet.add_cell(row_index, 6, transaction.type_id)
    add_border_to_cell worksheet, row_index, 6
  end

  def fill_data_result worksheet, row_index
    worksheet.add_cell(row_index, 8, @summary_income)
    add_border_to_cell worksheet, row_index, 8
    worksheet.add_cell(row_index, 9, @summary_expense)
    add_border_to_cell worksheet, row_index, 9
    worksheet.add_cell(row_index, 10, @summary_saved)
    add_border_to_cell worksheet, row_index, 10
    worksheet.sheet_data[row_index][10].change_border(:right, 'thin')
  end

  def add_border_to_cell sheet, row, col
    sheet.sheet_data[row][col].change_border(:bottom, 'thin')
    sheet.sheet_data[row][col].change_border(:left, 'thin')
    if sheet.sheet_name == "Transaction" && col == 6
      sheet.sheet_data[row][col].change_border(:right, 'thin')
    end

    if sheet.sheet_name == "Master" 
      if col == 3 || col == 7
        sheet.sheet_data[row][col].change_border(:right, 'thin')
      end
    end
  end

  def fill_data_sheet_transaction worksheet
    row_index = 4
    count = 1

    fill_data_result worksheet, row_index

    if @transactions.any?
      @transactions.each do |transaction|
        fill_data_row worksheet, row_index, transaction, count
        row_index += 1
        count += 1
      end
    end

    (1..6).each do |col|
      worksheet.change_column_horizontal_alignment(col, 'left')   
    end
  end

  def fill_data_sheet_master sheet_master
    row_index = 4
    @master_types.each {|key, value|
      sheet_master.add_cell(row_index, 6, value)
      sheet_master.change_column_horizontal_alignment(6, 'left')
      add_border_to_cell sheet_master, row_index, 6

      sheet_master.add_cell(row_index, 7, key)
      add_border_to_cell sheet_master, row_index, 7

      row_index += 1
    }

    row_index = 4
    @group_members.each do |group_member|
      sheet_master.add_cell(row_index, 1, group_member.user.id)
      sheet_master.change_column_horizontal_alignment(1, 'left')
      add_border_to_cell sheet_master, row_index, 1

      sheet_master.add_cell(row_index, 2, group_member.user.full_name)
      add_border_to_cell sheet_master, row_index, 2

      sheet_master.add_cell(row_index, 3, group_member.user.email)
      add_border_to_cell sheet_master, row_index, 3

      row_index += 1
    end
  end
end

app/views/transactions/_current_money.html.erb
<div class="col-md-12 current_money text-align-center">
  <% number = number_to_currency(@current_money, :unit => "đ ") %>
  <%= t("common.current_money") %>
  
  <% if @current_money.to_i > 0 %>
    <span class="income">+ <%= number %></span>
  <% elsif @current_money.to_i == 0 %>
    <span class="income"><%= number %></span>
  <% else %>
    <span class="expense"><%= number %></span>
  <% end %>
</div>

app/views/transactions/_form.html.erb
 <div class="modal fade" id="transaction_form" tabindex="-1" role="dialog" 
  aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          &times;
        </button>

        <h5 class="modal-title" id="transaction_form_title">
          <%= t("model.transaction.title.add") %>
        </h5>
      </div>

      <%= form_with model: Transaction, url: group_transactions_path, 
        :html=> {:class => "form-horizontal", :id => "frm_transaction"} do |f| %>
        <%= f.hidden_field :transaction_id, id: "transaction_id", value: 0 %>

        <div class="modal-body modal-body-custom">
          <div class="form-group">
            <div class="col-md-3 col-xs-3 control-label">
              <%= t("model.transaction.type.type_id")%>
            </div>

            <div class="col-md-8 col-xs-8">
              <%= f.radio_button :type_id, 1, class: "type_id", id: "type_expense", :checked => true %> 
              <%= label :type_id, t("model.transaction.type.list_type.expense") %>
              <%= f.radio_button :type_id, 2, class: "type_id", id: "type_income" %>
              <%= label :type_id, t("model.transaction.type.list_type.income") %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-3 col-xs-3 control-label">
              <%= t("model.transaction.type.amount")%>
              <span class="require">(*)</span>
            </div>

            <div class="col-md-8 col-xs-8">
              <%= f.text_field :amount, {class: "form-control validate[required, custom[number]]", 
                id: "amount", placeholder: "đ"} %>
            </div>
          </div>

          <div class="form-group income_hidden" id="category_select_box">
            <div class="col-md-3 col-xs-3 control-label">
              <%= t("model.transaction.type.category_id")%>
              <span class="require">(*)</span>
            </div>

            <div class="col-md-8 col-xs-8 custom-chosen">
              <%= f.collection_select :category_id, @categories, :id, :name.to_s,
                {prompt: false}, {class: "chosen-select form-control validate[required]", 
                id: "category_id"} %>
            </div>
          </div>

          <div class="form-group income_hidden" id="product_box">
            <%= render "product_checkbox" %>
          </div>

          <div class="form-group">
            <div class="col-md-3 col-xs-3 control-label">
              <%= t("model.transaction.type.description")%>
            </div>

            <div class="col-md-8 col-xs-8">
              <%= f.text_area :description, {class: "form-control custom-scroll", 
                placeholder: t('model.transaction.type.description'), rows: 3, id: "description"} %>
            </div>
          </div>
        </div>

        <div class="modal-footer modal-footer-custom">
          <div class="col-md-offset-3 col-md-9">
            <button type="button" class="btn custom-btn-green btn-submit" 
              id="transaction_form_button">
              <%= t("common.form.add") %></button>
            <button type="button" class="btn btn-default cancel" data-dismiss="modal">
              <%= t("common.form.cancel") %>
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/transactions/_list.html.erb
<%= render "summary" %> 

<div class="col-md-12 table-responsive" id="table_wapper">
  <div class="row">
    <table class="table table-striped table-bordered table-hover dataTable 
      no-footer display" id="table_transaction">
      <thead>
        <tr>
          <th width="7%"><%= t("common.form.no") %></th>
          <th width="13%"><%= t("model.transaction.type.created_at") %></th>
          <th width="15%"><%= t("model.transaction.type.amount") %></th>
          <th><%= t("model.transaction.type.description") %></th>
          <th width="20%"><%= t("model.transaction.type.update_by_user") %></th>
          <th width="10%"><%= t("model.transaction.type.type_id") %></th>
          <th width="8%"><%= t("common.form.action") %></th>
        </tr>
      </thead>

      <tbody id="row-table-transactions">
        <% if @transactions.any? %>
          <% @start_count = 1 %>

          <% @transactions.each do |transaction| %>
            <tr>
              <td><%= @start_count %></td>
              <td><%= transaction.updated_at.strftime("%m/%d/%Y") %></td>
              <td>
                <% number = number_to_currency(transaction.amount, :unit => "đ ") %>
                <% if transaction.type_id == "Expense" %>
                  <span class="expense">- <%= number %></span>
                <% else %>
                  <span class="income">+ <%= number %></span>
                <% end %>  
              </td>
              <td><%= transaction.description %></td>
              <td><%= transaction.user.full_name %></td>
              <td><%= transaction.type_id %></td>
              <td>
                <a href="#" data-toggle="modal" data-target="#transaction_form" 
                  class="transaction_edit" data-id="<%= transaction.id %>">
                  <i class="fa fa-pencil-square-o custom-action-icon-green
                    custom-action-icon-edit">
                  </i>
                </a>

                <a href="javascript: void(0)" class="transaction_delete" 
                  data-id="<%= transaction.id %>">
                  <i class="glyphicon glyphicon-trash glyphicon" 
                    data-id="<%= transaction.id %>"></i>
                </a>
              </td>
            </tr>

            <% @start_count += 1 %>
          <% end %>
        <% else %>
          <tr>
            <td colspan="7" align="center"><%= t("common.table.empty") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= render "current_money" %>

app/views/transactions/_script.html.erb
<% content_for :scripts do %>
  <script type="application/javascript">
    var group_id = <%= params[:group_id] %>

    $(document).ready(function() {
      initChosen("category_id");
      initChosen("transaction_category_id");
      setParamsSearch();

      $("#frm_transaction").validationEngine({
        promptPosition: "inline",
        addSuccessCssClassToField: "no-error",
        addFailureCssClassToField: "has-error",
        validateNonVisibleFields: true,
        prettySelect : true,
        useSuffix: "_chosen"
      });

      $("#frm_search_transaction").validationEngine({
        promptPosition: "inline",
        addSuccessCssClassToField: "no-error",
        addFailureCssClassToField: "has-error",
        validateNonVisibleFields: true
      });

      $("input[type=radio][name='transaction[type_id]']").on("change", function() {
        if (this.value == "1") {
          resetForm();
          $(".income_hidden").show();
          $("#category_id").addClass("validate[required]");
        } else if (this.value == "2") {
          resetForm();
          $(".income_hidden").hide();
          $("#category_id").removeClass("validate[required]");
        }
      });

      $("#frm_transaction").on("change", "#category_id", function() {
        var category_id = $(this).val();
        $("#description").val("");
        
        if (category_id > 0) {
          $("#product_box").show();
          getProductByCategory(category_id);
        } else {
          $("#product_box").hide();
        }
      });

      $("#frm_transaction").on("change", "input:checkbox", function() {
        displayDescription();    
      });

      $(".transaction_add").on("click", function() {
        resetForm();
        $("#transaction_form_title").html("<%= t('model.transaction.title.add') %>");
        $("#transaction_form_button").html("<%= t('common.form.add') %>");
        $(".type_id").prop("disabled", false);
      });

      $("#list_transaction").on("click", ".transaction_edit", function() {
        resetForm();
        $("#transaction_form_title").html("<%= t('model.transaction.title.update') %>");
        $("#transaction_form_button").html("<%= t('common.form.update') %>");

        var id = $(this).data("id");
        showFormEdit(id);
      });

      $("#transaction_form_button").on("click", function() {
        onSave();
      });

      $("#list_transaction").on("click", ".transaction_delete", function() {
        resetForm();
        var id = $(this).data("id");
        displayDialogDelete(id);
      });

      $("#frm_search_transaction").on("click", ".reset", function() {
        resetSearch();
      });

      $("#frm_search_transaction").on("click", ".search", function() {
        var url = "<%= group_transactions_path %>";
        $("#frm_search_transaction").attr("action", url).submit();
      });

      $("#frm_search_transaction").on("click", ".export", function() {
        var url = "<%= group_export_transactions_path %>";
        $("#frm_search_transaction").attr("action", url).submit();
      });
    });

    function setParamsSearch() {
      <% unless params[:from_date].blank? %>
        var from_date = moment('<%= params[:from_date] %>').format('L');
      <% else %>
        var from_date = "";
      <% end %>

      <% unless params[:to_date].blank? %>
        var to_date = moment('<%= params[:to_date] %>').format('L');
      <% else %>
        var to_date = "";
      <% end %>

      <% unless params[:type_id].blank? %>
        var type_id = "<%= params[:type_id] %>";
      <% else %>
        var type_id = 0;
      <% end %>

      <% unless params[:category_id].blank? %>
        var category_id = "<%= params[:category_id] %>";
      <% else %>
        var category_id = 0;
      <% end %>

      $("#start_date").val(from_date);
      $("#end_date").val(to_date);
      $("#transaction_type_id").val(type_id);
      $("#transaction_category_id").val(category_id);
      $("#transaction_category_id").trigger("chosen:updated");
    }

    function resetForm() {
      $("#amount").val("");
      $("input:checkbox").removeAttr('checked');
      $("#description").val("");
      $("#category_id").val("");
      $("#category_id").trigger("chosen:updated");
      $("#product_box").hide();

      removeStyleErrorValidate();
    }

    function resetSearch() {
      $("#start_date").val("");
      $("#end_date").val("");
      $("#transaction_type_id").val(0);
      $("#transaction_category_id").val(0);
      $("#transaction_category_id").trigger("chosen:updated");
    }

    function getProductByCategory(category_id) {
      data = {
        category_id: category_id,
        group_id: group_id
      };
      url = "/groups/" + group_id + "/products/post_product_by_category";

      $.ajax({
        url: url,
        data: data,
        cache: false,
        type: "POST",
        success: function(data){
          $("#product_box").html(data);
        }
      });
    }

    function showFormEdit(id) {
      data = {id: id};
      url = "/groups/" + group_id + "/transactions/get_transaction";

      $.ajax({
        url: url,
        data: data,
        cache: false,
        type: "POST",
        success: function(data){
          $("#transaction_id").val(id);
          $("#amount").val(data.amount);
          $("#category_id").val(data.category_id);
          $("#category_id").trigger("chosen:updated");
          $("#description").val(data.description);

          if (data.type_id == "Expense") {
            $("#type_expense").prop("checked", true);
            $(".income_hidden").show();
            $("#type_expense").prop("disabled", false);
            $("#type_income").prop("disabled", true);
            $("#product_box").hide();
            $("#category_id").addClass("validate[required]");
          } else {
            $("#type_income").prop("checked", true);
            $(".income_hidden").hide();
            $("#type_expense").prop("disabled", true);
            $("#type_income").prop("disabled", false);
            $("#category_id").removeClass("validate[required]");
          }
        }
      });
    }

    function onSave() {
      var status = $("#frm_transaction").validationEngine("validate");
  
      if(status == false){
        return status;
      }

      var data = $("#frm_transaction").serialize();
      var id = $("#transaction_id").val();

      if (id > 0) {
        $.ajax({
          url: "/groups/" + group_id + "/transactions/" + id,
          data: data,
          cache: false,
          type: "PATCH",
          success: function(data){
            // $("#transaction_form").modal('toggle');
            // $("#list_transaction").html(data);
            // var message = "<%= t('model.transaction.message.update_success') %>";
            // displayDialogSuccess(message);
            
            window.location.replace("<%= group_transactions_path %>");
          }
        });
      } else {
        $.ajax({
          url: "/groups/" + group_id + "/transactions",
          data: data,
          cache: false,
          type: "POST",
          success: function(data){
            // $("#transaction_form").modal('toggle');
            // $("#list_transaction").html(data);
            // var message = "<%= t('model.transaction.message.add_success') %>";
            // displayDialogSuccess(message);

            window.location.replace("<%= group_transactions_path %>");
          }
        });
      }

      return true;
    }

    function displayDialogDelete(id) {
      $("#dialog-messages").dialog({
        closeOnEscape: false,
        open: function(event, ui) {
          $("#lblmessages").html("<%= t('common.form.delete_confirm_msg') %>");
          $("#dialog-messages .alert").addClass("alert-warning");
          $(".ui-dialog-titlebar-close", ui.dialog | ui)
            .css("margin-top", "-10px")
            .css("margin-right", "4px")
            .css("color", "red");
        },
        width: 400,
        modal: true,
        buttons: [
          {
            id: "btnCancel",
            text: "<%= t('common.form.delete') %>",
            class: "btn btn-danger",
            click: function () {
              data = {
                id: id
              };
              url = "/groups/" + group_id + "/transactions/" + id;

              $.ajax({
                url: url,
                data: data,
                cache: false,
                type: "DELETE",
                success: function (data) {
                  // $("#list_transaction").html(data);
                  // var message = "<%= t('model.transaction.message.deleted_success') %>";
                  // displayDialogSuccess(message); 

                  window.location.replace("<%= group_transactions_path %>");
                }
              });
              $(this).dialog('close');
            }
          },
          {
            id: "btnCancel",
            text: "<%= t('common.form.cancel') %>",
            class: "btn btn-default",
            click: function () {
              $(this).dialog('close');
            }
          }
        ]
      });
    }

    function displayDescription() {
      var list_product_name = "";

      $("input[type=checkbox]").each(function () {          
        if(this.checked) {
          var product_id = $(this).parent().data("product-id");
          product_name = $("#product_name_" + product_id).html();
          if (list_product_name != "") {
            list_product_name += ", "
          }
          list_product_name += $.trim(product_name)
        }
      });

      $("#description").val(list_product_name);
    }

    function displayDialogSuccess(message) {
      $("#dialog-success").dialog({
        closeOnEscape: false,
        open: function(event, ui) {
          $("#message-success").html(message);
          $("#dialog-success .alert").addClass("alert-success");
          $(".ui-dialog-titlebar-close", ui.dialog | ui)
            .css("margin-top", "-10px")
            .css("margin-right", "4px")
            .css("color", "red");
        },
        width: 400,
        modal: true
      });
    }
  </script>
<% end %>

app/views/transactions/index.html.erb
<% content_for :ribbon do %>
  <div id="ribbon">
    <a href="<%= root_path %>"><i class="fa fa fa-money"></i></a>
    <ol class="breadcrumb">
      <li>
        <a href="<%= group_transactions_path %>">
          <%= t("model.transaction.model_name") %>
        </a>
      </li>
    </ol>
  </div>
<% end %>

<article class="col-sm-12 col-md-12 col-lg-12">
  <div class="custom-widget">
    <header role="heading">
      <div class="col-xs-8 title">
        <h5>
          <%= t("model.transaction.title.list") %>
        </h5>
      </div>

      <div class="col-xs-4">
        <span class="btn custom-btn-green btn-add pull-right transaction_add" 
          data-toggle="modal" data-target="#transaction_form">
          <%= t("common.form.add") %>
        </span>
      </div>
    </header>

    <div class="wg-content">
      <div class="row search-content" id="transaction-search">
        <%= render "search" %>
      </div>
      <div class="row listing-container" id="list_transaction">
        <%= render "list" %>
      </div>
    </div>
  </div>
</article>

<% if @transactions.any? %>
  <%= render "script_datatable" %>
<% end %>

<%= render "form" %>
<%= render "shared/dialog"%>
<%= render "shared/dialog_success"%>
<%= render "script" %>